### ISSUE TITLE
License for use

### ISSUE THREAD

**Issue by intrepidOlivia** [jacopofar/wordnet-as-a-service#1]
Hello, I was wondering what kind of license this code is under?

**Comment by jacopofar** [comment]
Good question :) The main component, extJWNL, has a BSD license. I think I can go with that

**Comment by jacopofar** [comment]
I added MIT as is more common and should be compatible with the dependencies. Enjoy :)

**Comment by intrepidOlivia** [comment]
Cool, thanks so much :)
